" Default Setting
set nu
set relativenumber
set si
set ai
set ci
set tabstop=4
set expandtab
set shiftwidth=4
set hlsearch
set incsearch
set clipboard=unnamedplus
set foldmethod=syntax
set foldlevel=100
if has("mac")
	set backspace=indent,eol,start
endif
syntax on
colorscheme koehler

" Key Map Setting
" PlugIn
map <C-k><C-b> :NERDTreeToggle<Enter>
map <C-k><C-o> :TagbarToggle<Enter>
nnoremap <C-k><C-m> :MarkdownPreview<Enter>
nnoremap <C-k><C-m><C-m> :MarkdownPreviewStop<Enter>
nnoremap <C-p> :FZF<Enter>

" Move Line
if has("mac")
	map <A-Up> :m .-2<Enter>==
	map <A-Down> :m .+1<Enter>==
	map ∆ <A-Down>
	map ˚ <A-Up>
elseif has("unix")
	" Recognize 'ALT' key
	" There are two way for a terminal emulator to send 'ALT' key (8 bit characters for 'ALT' or escape sequences, ALT-A as ESC-A)
	let c='a'
	while c <= 'z'
	  exec "set <A-".c.">=\e".c
	  exec "imap \e".c." <A-".c.">"
	  let c = nr2char(1+char2nr(c))
	endw
	set timeout ttimeoutlen=50

	nnoremap <A-k> :m .-2<Enter>==
	nnoremap <A-j> :m .+1<Enter>==
	map <A-Down> <A-j>
	map <A-Up> <A-k>
endif
vnoremap <A-j> :'<,'>m '>+1<Enter>gv=gv
vnoremap <A-k> :'<,'>m '<-2<Enter>gv=gv
vmap <A-Up> <A-k>
vmap <A-Down> <A-j>

" Indent
vnoremap < <gv
vnoremap > >gv

" Bracket
inoremap { {}<Esc>i

" Edit
nnoremap <Space> i<Space><Esc>
nnoremap <Enter> i<Enter><Esc>

" Plugin Setting
set nocompatible
filetype off

set rtp+=/usr/local/opt/fzf
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'valloric/youcompleteme'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-airline/vim-airline'
Plugin 'keith/swift.vim'
Plugin 'udalov/kotlin-vim'
Plugin 'iamcco/mathjax-support-for-mkdp'
Plugin 'iamcco/markdown-preview.vim'
Plugin 'ZoomWin'
Plugin 'mattn/emmet-vim'
Plugin 'ap/vim-css-color'

call vundle#end()
filetype plugin indent on

" Syntastic Setting
let g:syntastic_cpp_compiler_options='-std=c++14'
